<#
.SYNOPSIS
    Verifies that a project's harness install is present and in sync.

.DESCRIPTION
    Checks two things that fail in opposite directions and are both easy to miss:

      - the .opencode artifacts exist at all;
      - the rules block in AGENTS.md is byte-identical to rules/global.md.

    The second check is the one that matters. Two copies of the same rules drift, and
    a stale copy is worse than none: it looks authoritative while being out of date.
    This was measured - a homework's copy had fallen 176 lines behind, missing every
    rule learned since, and nothing reported it.

    Exit code 0 = in sync, 1 = drift or missing.

.EXAMPLE
    powershell -File check.ps1 -Project D:\some\project
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$Project
)

$ErrorActionPreference = 'Stop'

$begin = '<!-- harness:begin global rules (generated by the harness installer; edit rules/global.md, not this block) -->'
$end = '<!-- harness:end -->'

$harnessRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$rulesPath = Join-Path $harnessRoot 'rules\global.md'
$problems = @()

if (-not (Test-Path -LiteralPath $Project)) {
    Write-Host "FAIL  project not found: $Project"
    exit 1
}

$opencodeDst = Join-Path $Project '.opencode'
if (-not (Test-Path -LiteralPath $opencodeDst)) {
    $problems += 'missing .opencode/ - run install.ps1'
} else {
    foreach ($sub in @('agent', 'command', 'skills')) {
        $src = Join-Path (Join-Path $harnessRoot '.opencode') $sub
        if (Test-Path -LiteralPath $src) {
            if (-not (Test-Path -LiteralPath (Join-Path $opencodeDst $sub))) {
                $problems += "missing .opencode/$sub"
            }
        }
    }
}

$agentsPath = Join-Path $Project 'AGENTS.md'
if (-not (Test-Path -LiteralPath $agentsPath)) {
    $problems += 'missing AGENTS.md - run install.ps1'
} else {
    $text = [System.IO.File]::ReadAllText($agentsPath, [Text.Encoding]::UTF8)
    $pattern = [regex]::Escape($begin) + '[\s\S]*?' + [regex]::Escape($end)
    $match = [regex]::Match($text, $pattern)
    if (-not $match.Success) {
        $problems += 'AGENTS.md has no harness rules block - run install.ps1'
    } else {
        $expected = [System.IO.File]::ReadAllText($rulesPath, [Text.Encoding]::UTF8).Trim()
        $actual = $match.Value
        $actual = $actual.Substring($begin.Length, $actual.Length - $begin.Length - $end.Length).Trim()
        if ($actual -cne $expected) {
            $expectedLines = ($expected -split "`n").Count
            $actualLines = ($actual -split "`n").Count
            $problems += "AGENTS.md rules block is stale (installed $actualLines lines, canonical $expectedLines) - run install.ps1"
        }
    }
    if ($text -match '[\uFFFD]{2,}') {
        $problems += 'AGENTS.md contains replacement characters - a repair script wrote mojibake as data'
    }
}

if ($problems.Count -eq 0) {
    Write-Host "OK    $Project is in sync"
    exit 0
}

Write-Host "DRIFT $Project"
foreach ($p in $problems) { Write-Host "  - $p" }
exit 1
