<#
.SYNOPSIS
    Installs this harness into a project: the opencode artifacts, and the global
    working rules into the project's AGENTS.md.

.DESCRIPTION
    Two separate things are installed, because they have different lifetimes:

      1. .opencode/  - agent, command and skill definitions. Copied verbatim.
      2. AGENTS.md   - the global rules, embedded verbatim between marker comments.

    The rules are embedded rather than referenced by path on purpose. A pointer is
    a single source of truth, but it depends on the agent choosing to follow it, and
    the whole point of this harness is that a rules file nobody reads is not a rules
    file. Embedding is safe only because check.ps1 compares the block against
    rules/global.md, so drift is detected instead of accumulating.

    The install is idempotent. Project-specific rules stay outside the markers and are
    never touched.

.PARAMETER Project
    Target project directory. Must exist.

.PARAMETER Force
    Overwrite existing .opencode artifacts even if they were modified locally.

.EXAMPLE
    powershell -File install.ps1 -Project D:\some\project
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$Project,
    [switch]$Force
)

$ErrorActionPreference = 'Stop'

$begin = '<!-- harness:begin global rules (generated by the harness installer; edit rules/global.md, not this block) -->'
$end = '<!-- harness:end -->'

$harnessRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$rulesPath = Join-Path $harnessRoot 'rules\global.md'
$opencodeSrc = Join-Path $harnessRoot '.opencode'

function Write-Step([string]$Message) { Write-Host "  $Message" }

if (-not (Test-Path -LiteralPath $Project)) {
    throw "project not found: $Project"
}
foreach ($required in @($rulesPath, $opencodeSrc)) {
    if (-not (Test-Path -LiteralPath $required)) {
        throw "harness is incomplete, missing: $required"
    }
}

Write-Host "Installing harness into $Project"

# --- 1. .opencode artifacts -----------------------------------------------------
$opencodeDst = Join-Path $Project '.opencode'
if (Test-Path -LiteralPath $opencodeDst) {
    foreach ($sub in @('agent', 'command', 'skills')) {
        $from = Join-Path $opencodeSrc $sub
        if (-not (Test-Path -LiteralPath $from)) { continue }
        $to = Join-Path $opencodeDst $sub
        if ((Test-Path -LiteralPath $to) -and -not $Force) {
            Write-Step "keep  .opencode/$sub (present; use -Force to overwrite)"
            continue
        }
        Copy-Item -LiteralPath $from -Destination $to -Recurse -Force
        Write-Step "copy  .opencode/$sub"
    }
} else {
    Copy-Item -LiteralPath $opencodeSrc -Destination $opencodeDst -Recurse
    Write-Step 'copy  .opencode'
}
foreach ($extra in @('.gitignore', 'package.json')) {
    $from = Join-Path $opencodeSrc $extra
    if (Test-Path -LiteralPath $from) {
        Copy-Item -LiteralPath $from -Destination (Join-Path $opencodeDst $extra) -Force
    }
}

# --- 2. rules into AGENTS.md ----------------------------------------------------
$agentsPath = Join-Path $Project 'AGENTS.md'
$rules = [System.IO.File]::ReadAllText($rulesPath, [Text.Encoding]::UTF8).Trim()
$block = "$begin`n$rules`n$end"

$existing = if (Test-Path -LiteralPath $agentsPath) {
    [System.IO.File]::ReadAllText($agentsPath, [Text.Encoding]::UTF8)
} else { '' }

$pattern = [regex]::Escape($begin) + '[\s\S]*?' + [regex]::Escape($end)

if ($existing -match $pattern) {
    # MatchEvaluator, not a replacement string: the rules text contains '$' and would
    # be treated as a substitution reference.
    $evaluator = [System.Text.RegularExpressions.MatchEvaluator] { param($m) $block }
    $updated = [regex]::Replace($existing, $pattern, $evaluator, 1)
    Write-Step 'update AGENTS.md rules block'
} else {
    $prefix = if ([string]::IsNullOrWhiteSpace($existing)) { "# Project instructions`n`n" } else { $existing.TrimEnd() + "`n`n" }
    $updated = $prefix + $block + "`n"
    Write-Step 'write AGENTS.md with rules block'
}

# No BOM: repository text files, and ReadAllText detects UTF-8 by itself.
[System.IO.File]::WriteAllText($agentsPath, $updated, (New-Object System.Text.UTF8Encoding $false))

Write-Host ''
Write-Host 'Done. Project-specific rules go BELOW the harness:end marker.'
Write-Host 'Run check.ps1 to verify the install is in sync.'
