version: '3.8'

services:
  web:
    build: .
    container_name: python_dev_container
    volumes:
      # Монтируем текущую директорию в /app, чтобы изменения кода сразу применялись
      - .:/app
    ports:
      # Порт, который будет использоваться (если мы хотим, чтобы скрипты были доступны снаружи)
      - "8000:8000" # Предполагаем, что приложение будет слушать порт 8000
    command: python src/main.py