services:
  llm_dev:
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    volumes:
      - .:/app:cached
      - ~/.cache:/root/.cache:cached
    ports:
      - "8000:8000"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    command: ["sleep", "infinity"]
