"""Documentation layers for prompt building.

Docs are gathered into labelled layers. A page about the API is only
"Context" (not a contract); ``contracts/base`` is the base / contract (XYZ);
``contracts/supplements`` are supplements (XXX) that override base. The
prompt is then assembled from these placeholders.
"""

from __future__ import annotations

import html
import json
import re
from dataclasses import dataclass, field
from typing import Any

import httpx
import yaml

_OPENAPI_KEYS = ("openapi", "swagger")
_BASE_UNSUPPORTED_NOTE = (
    "Базовая OpenAPI-спека недоступна — контракт собирается из дополнений и "
    "описания страницы, маркеры покрытия определяются по перечисленным ресурсам."
)
_NO_SPECS_NOTE = (
    "Ни спек, ни дополнений нет — режим best effort: маркеры покрытия по "
    "глаголам/ручным --required-resources."
)


class DocsError(ValueError):
    """Documentation source could not be loaded/enumerated."""


@dataclass(frozen=True)
class Layer:
    """A labelled documentation slice with a merge priority."""

    name: str
    content: str
    priority: int = 0  # higher overrides lower; XXX (supplements) > XYZ (base)
    is_contract: bool = False

    def header(self) -> str:
        return f"<!-- слой: {self.name} -->"


@dataclass
class DocBundle:
    """All documentation layers assembled for the prompt."""

    context: str = ""
    base: Layer | None = None
    supplements: list[Layer] = field(default_factory=list)
    mode: str = "none"
    markers: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    def merged_contract(self) -> str:
        """Merge base + supplements into one contract string, XXX overriding XYZ."""
        parts: list[str] = []
        base_header = None
        base_lines: dict[str, str] = {}
        supp_lines: dict[str, str] = {}
        if self.base is not None:
            base_header = self.base.header()
            base_lines = _split_lines(self.base.content)
        for supp in self.supplements:
            for key, val in _split_lines(supp.content).items():
                supp_lines[key] = val
        conflicts = sorted(base_lines.keys() & supp_lines.keys())
        for key, val in base_lines.items():
            if key in supp_lines:
                base_lines[key] = f"{val}  ← переопределено дополнением"
        if base_header:
            parts.append(base_header)
        merged: dict[str, str] = {}
        merged.update(base_lines)
        merged.update({k: v for k, v in supp_lines.items() if k not in base_lines})
        for key, val in merged.items():
            parts.append(f"- **`{key}`**: {val}")
        if conflicts:
            self.warnings.append(
                "Конфликты (XYZ↔XXX) разрешаются в пользу дополнения (XXX): " + ", ".join(conflicts)
            )
        return "\n".join(p for p in parts if p)


def _split_lines(content: str) -> dict[str, str]:
    """Parse simple '`key` — value' or 'key: value' lines into a map."""
    out: dict[str, str] = {}
    for line in content.splitlines():
        line = line.strip()
        if not line:
            continue
        m = re.match(r"^`?([A-Za-z0-9_\-/]+)`?\s*[:—‑]\s*(.+)$", line)
        if m:
            out[m.group(1)] = m.group(2)
    return out


# --- detection ---------------------------------------------------------


def detect_source(text: str, *, name: str = "") -> str:
    """Classify a documentation string: 'openapi' | 'markdown'."""
    stripped = text.lstrip()
    if stripped.startswith(("{", "[")):
        try:
            data = json.loads(stripped)
            if isinstance(data, dict) and any(k in data for k in _OPENAPI_KEYS):
                return "openapi"
        except ValueError:
            pass
    try:
        data = yaml.safe_load(stripped)
        if isinstance(data, dict) and any(k in data for k in _OPENAPI_KEYS):
            return "openapi"
    except yaml.YAMLError:
        pass
    return "markdown"


def is_url(value: str) -> bool:
    return value.strip().startswith(("http://", "https://"))


# --- OpenAPI enumeration -------------------------------------------------


def parse_openapi(text: str) -> dict[str, Any]:
    try:
        data = json.loads(text)
    except ValueError:
        try:
            data = yaml.safe_load(text)
        except yaml.YAMLError as exc:
            raise DocsError(f"не удалось разобрать OpenAPI-спеку: {exc}") from exc
    if not isinstance(data, dict) or not any(k in data for k in _OPENAPI_KEYS):
        raise DocsError("документ не похож на OpenAPI-спеку")
    return data


def openapi_digest(spec: dict[str, Any]) -> Layer:
    """Structural listing path→methods→codes→schemas + autogenerated markers."""
    lines: list[str] = []
    markers: list[str] = []
    paths = spec.get("paths") or {}
    for path in sorted(paths):
        for method in sorted(paths[path]):
            if method.lower() not in ("get", "post", "put", "patch", "delete", "head", "options"):
                continue
            op = paths[path][method]
            codes = sorted(str(c) for c in (op.get("responses") or {}))
            lines.append(
                f"- `{method.upper()} {path}` — коды: {', '.join(codes) or '—'}"
            )
            marker = path.strip("/").split("/")[0]
            if marker:
                markers.append(marker.lower())
    lines.append("")
    lines.append("_Маркеры покрытия (автогенерация): " + ", ".join(sorted(set(markers))) + "_")
    return Layer(name="contracts/base (OpenAPI)", content="\n".join(lines), priority=10, is_contract=True)


# --- URL page ------------------------------------------------------------


def fetch_url_page(url: str, *, transport: httpx.BaseTransport | None = None, limit: int = 8000) -> str:
    """Download a doc page, strip HTML, truncate to ``limit`` chars."""
    with httpx.Client(follow_redirects=True, timeout=30.0, transport=transport) as client:
        resp = client.get(url)
        resp.raise_for_status()
        raw = resp.text
    text = re.sub(r"<script.*?</script>", " ", raw, flags=re.DOTALL | re.IGNORECASE)
    text = re.sub(r"<style.*?</style>", " ", text, flags=re.DOTALL | re.IGNORECASE)
    text = re.sub(r"<[^>]+>", " ", text)
    text = html.unescape(re.sub(r"\s+", " ", text)).strip()
    if len(text) > limit:
        text = text[:limit] + " …(выжимка ограничена)"
    return text


# --- bundle assembly ------------------------------------------------------


def build_bundle(
    *,
    api_page: str = "",
    base_text: str | None = None,
    supplement_texts: list[str] | None = None,
) -> DocBundle:
    """Assemble the doc layers and compute the documentation mode.

    Combos (per the spec): API+XYZ; API+XXX(no XYZ); API+XYZ+XXX; API only.
    """
    supplements = list(supplement_texts or [])
    bundle = DocBundle(
        context=api_page.strip(),
        mode="api-only",
    )

    if base_text:
        kind = detect_source(base_text)
        if kind == "openapi":
            try:
                bundle.base = openapi_digest(parse_openapi(base_text))
                bundle.mode = "api+xyz"
            except DocsError as exc:
                bundle.warnings.append(str(exc))
                bundle.base = Layer(
                    name="contracts/base (текст)", content=base_text.strip(), priority=10, is_contract=True
                )
        else:
            bundle.base = Layer(
                name="contracts/base (markdown)", content=base_text.strip(), priority=10, is_contract=True
            )

    for i, sup in enumerate(supplements):
        bundle.supplements.append(
            Layer(name=f"contracts/supplements/{i}", content=sup.strip(), priority=20, is_contract=True)
        )

    if bundle.base is not None and supplements:
        bundle.mode = "api+xyz+xxx"
    elif bundle.base is None and supplements:
        bundle.mode = "api+xxx"
        bundle.warnings.append(_BASE_UNSUPPORTED_NOTE)
        if not bundle.context:
            bundle.warnings.append(_NO_SPECS_NOTE)

    # Collect markers for coverage.
    raw_markers: list[str] = []
    if bundle.base is not None:
        for m in re.findall(r"маркеры покрытия.*?[:：] (.*?)_", bundle.base.content):
            raw_markers += [x.strip() for x in m.split(",") if x.strip()]
    for layer in bundle.supplements:
        raw_markers += _extract_markers(layer.content)
    bundle.markers = sorted(set(raw_markers))

    if bundle.base is None and not supplements and not api_page:
        bundle.mode = "none"
        bundle.warnings.append(_NO_SPECS_NOTE)
    elif bundle.base is None and not supplements and api_page:
        bundle.mode = "api-only"

    return bundle


def _extract_markers(content: str) -> list[str]:
    m = re.search(r"маркеры покрытия.*?[:：] (.*?)(_|$)", content)
    if not m:
        return []
    return [x.strip() for x in m.group(1).split(",") if x.strip()]


def build_prompt(
    template: str,
    *,
    context: str,
    base_content: str,
    supplements_content: str,
    service: str,
    schema_version: str,
) -> str:
    """Fill the prompt template placeholders."""
    return (
        template.replace("{docs_context}", context or "—")
        .replace("{contracts_base}", base_content or "—")
        .replace("{contracts_supplements}", supplements_content or "—")
        .replace("{service}", service)
        .replace("{schema_version}", schema_version)
    )
